'use client';

import React, { useState } from 'react';
import { Info } from 'lucide-react';

export const METRIC_DEFINITIONS: Record<string, { label: string; formula: string; desc: string }> = {
  cagr: {
    label: 'CAGR (Compound Annual Growth Rate)',
    formula: '((V_end / V_start) ^ (1 / n)) - 1',
    desc: 'The annualized rate of geometric return that would take an investment from its beginning balance to its ending balance over the full duration.',
  },
  volatility: {
    label: 'Annualized Volatility (StDev)',
    formula: 'sigma_monthly * sqrt(12)',
    desc: 'The dispersion of monthly returns annualized by multiplying the sample standard deviation by the square root of 12. Measures total price variability.',
  },
  sharpeRatio: {
    label: 'Sharpe Ratio',
    formula: '(CAGR - Rf) / AnnualizedVolatility',
    desc: 'Measures excess return earned above the risk-free rate per unit of total risk (volatility). Higher values indicate superior risk-adjusted reward.',
  },
  sortinoRatio: {
    label: 'Sortino Ratio',
    formula: '(CAGR - Rf) / DownsideDeviation',
    desc: 'A modification of the Sharpe ratio that penalizes only downside volatility below a target return (0% or Rf), without penalizing upside price surges.',
  },
  calmarRatio: {
    label: 'Calmar Ratio',
    formula: 'CAGR / abs(MaximumDrawdown)',
    desc: 'Measures return relative to worst-case historical pain. Compares annual compounding against the deepest peak-to-trough loss.',
  },
  maxDrawdown: {
    label: 'Maximum Drawdown',
    formula: 'min_t ((V_t - Peak_t) / Peak_t)',
    desc: 'The deepest peak-to-trough decline experienced by the portfolio before a new historical high-water mark was attained.',
  },
  ulcerIndex: {
    label: 'Ulcer Index',
    formula: 'sqrt( (1 / N) * sum(DD_i^2) ) * 100',
    desc: 'Measures both the depth and duration of drawdowns. Penalizes extended prolonged slumps far more heavily than brief market dips.',
  },
  var95: {
    label: 'Historical VaR (95% Confidence)',
    formula: '5th percentile of historical monthly returns',
    desc: 'The worst monthly loss expected to occur in 95 out of 100 months under normal historical conditions.',
  },
  cvar95: {
    label: 'Conditional VaR (CVaR / Expected Shortfall)',
    formula: 'E(R | R <= VaR_95)',
    desc: 'The average loss incurred in the worst 5% tail events. Answers: "When the market crashes beyond VaR, how bad is the loss on average?"',
  },
  beta: {
    label: 'Beta (Market Sensitivity)',
    formula: 'Cov(R_p, R_b) / Var(R_b)',
    desc: 'A measure of systematic market risk. A Beta of 1.0 indicates matching benchmark swings, while Beta < 1.0 indicates defensive lower sensitivity.',
  },
  alpha: {
    label: "Jensen's Alpha",
    formula: 'CAGR_p - (Rf + Beta * (CAGR_b - Rf))',
    desc: 'The active excess return generated by the portfolio beyond what would be predicted by the Capital Asset Pricing Model (CAPM) given its market exposure.',
  },
  trackingError: {
    label: 'Tracking Error',
    formula: 'sigma(R_p - R_b) * sqrt(12)',
    desc: 'The annualized standard deviation of excess returns relative to the benchmark. Measures active management risk and deviation.',
  },
  informationRatio: {
    label: 'Information Ratio',
    formula: '(CAGR_p - CAGR_b) / TrackingError',
    desc: 'The active return achieved per unit of active benchmark tracking risk. Evaluates manager consistency in outperforming.',
  },
  treynorRatio: {
    label: 'Treynor Ratio',
    formula: '(CAGR_p - Rf) / Beta',
    desc: 'Measures excess return earned per unit of systematic market risk (Beta).',
  },
  upCapture: {
    label: 'Up-Market Capture Ratio',
    formula: '(CAGR_p_up / CAGR_b_up) * 100%',
    desc: 'Percentage of the benchmark gain captured when the benchmark has positive returns. Higher is better (> 100% outperforms up-markets).',
  },
  downCapture: {
    label: 'Down-Market Capture Ratio',
    formula: '(CAGR_p_down / CAGR_b_down) * 100%',
    desc: 'Percentage of the benchmark loss absorbed when the benchmark declines. Lower is better (< 100% protects capital in bear markets).',
  },
};

export function MetricTooltip({ metricKey, children }: { metricKey: string; children?: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  const def = METRIC_DEFINITIONS[metricKey];
  if (!def) return <>{children}</>;

  return (
    <span className="relative inline-flex items-center gap-1 group">
      {children}
      <button
        type="button"
        onMouseEnter={() => setOpen(true)}
        onMouseLeave={() => setOpen(false)}
        onClick={() => setOpen(!open)}
        className="text-slate-400 hover:text-sky-400 transition-colors focus:outline-none"
        aria-label={`Info about ${def.label}`}
      >
        <Info className="w-3.5 h-3.5" />
      </button>

      {open && (
        <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-72 p-3 bg-slate-900/95 backdrop-blur-md border border-slate-700/80 rounded-lg shadow-2xl z-50 text-xs text-slate-200 pointer-events-none transition-all">
          <div className="font-semibold text-sky-400 border-b border-slate-800 pb-1 mb-1.5">
            {def.label}
          </div>
          <p className="text-slate-300 leading-relaxed mb-2">{def.desc}</p>
          <div className="bg-slate-950/80 p-1.5 rounded font-mono text-[11px] text-teal-400 border border-slate-800/80">
            <span className="text-slate-500 mr-1">Formula:</span> {def.formula}
          </div>
        </div>
      )}
    </span>
  );
}
